server:
  port: 8080

spring:
  application:
    name: article-service
  datasource:
    # H2 DB 드라이버 클래스
    driver-class-name: org.h2.Driver
    # H2 메모리 DB URL. "mem:testdb"는 'testdb'라는 이름의 메모리 DB를 생성합니다.
    url: jdbc:h2:mem:testdb
    # H2 DB의 기본 사용자명
    username: sa
    # H2 DB의 기본 비밀번호는 비워둡니다.
    password:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    #url: jdbc:mysql://127.0.0.1:3306/mydatabase
#    username: myuser
#    password: secret
  jpa:
#    database-platform: org.hibernate.dialect.MySQLDialect
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update
